spring.datasource.url: jdbc:h2:mem:testdb
spring.h2.console.enabled: true
camunda.bpm.admin-user:
  id: admin
  password: admin
spring:
  datasource:
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
